trigger:
- main

pr:
- main

resources:
  repositories:
  - repository: azure_template
    type: github
    name: mdolab/.github
    endpoint: mdolab

extends:
  template: azure/azure_template.yaml@azure_template
  parameters:
    REPO_NAME: pysurf
    GCC_CONFIG: config/defaults/config_LINUX_GFORTRAN.mk
    INTEL_CONFIG: config/defaults/config_LINUX_INTEL.mk
    IMAGE: public
    COVERAGE: true
    TAPENADE: true
    TAPENADE_VERSION: "3.16"
    FPRETTIFY: true
