from baseClasses import Component
from TSurf.python.tsurf_component import TSurfComponent
from TSurf.python.tsurf_intersection import compute_intersections
from GeoMACHSurf.geomach_component import GeoMACHComponent
