1 Command: Procedure smoothing_main understood as hypsurfmain.smoothing_main
2 Command: Procedure computematrices_main understood as hypsurfmain.computematrices_main
3 Command: Procedure areafactor understood as hypsurfmain.areafactor
4 Command: Procedure findradius understood as hypsurfmain.findradius
5 Command: Procedure findratio understood as hypsurfmain.findratio
6 Command: unit march_main: not found
7 hypsurfmain: (DD15) Module precision is not defined
8 computematrices_main: (DD15) Module solveroutines is not defined
9 computematrices_main: (TC33) External procedure solve is not declared
10 computematrices_main: Command: Input variable(s) f have their derivative modified in computematrices_main: added to independents
11 computematrices_main: (AD09) Please provide a differential of function solve for arguments Arg1=(in) Arg2=(in;out) Arg3=(in)
12 areafactor: Command: Input variable(s) s have their derivative modified in areafactor: added to independents
13 smoothing_main: Command: Input variable(s) rout have their derivative modified in smoothing_main: added to independents
14 qualitycheck: (TC19) Equality test on reals is not reliable
15 findradius: Command: Input variable(s) radius have their derivative modified in findradius: added to independents
16 findratio: Command: Input variable(s) q have their derivative modified in findratio: added to independents
17 giveangle: (TC16) Type mismatch in assignment: REAL,kind=realtype  receives DOUBLE PRECISION
