1 Command: Procedure smoothing_main understood as hypsurfmain.smoothing_main
2 Command: Procedure computematrices_main understood as hypsurfmain.computematrices_main
3 Command: Procedure areafactor understood as hypsurfmain.areafactor
4 Command: Procedure findradius understood as hypsurfmain.findradius
5 Command: Procedure findratio understood as hypsurfmain.findratio
6 Command: Procedure march_main understood as hypsurfmain.march_main
7 hypsurfmain: (DD15) Module precision is not defined
8 qualitycheck: (TC19) Equality test on reals is not reliable
9 computematrices_main: (DD15) Module solveroutines is not defined
10 computematrices_main: (TC33) External procedure solve is not declared
11 computematrices_main: (AD09) Please provide a differential of function solve for arguments Arg1=(in) Arg2=(in;out) Arg3=(in)
12 giveangle: (TC16) Type mismatch in assignment: REAL,kind=realtype  receives DOUBLE PRECISION
