1 Command: Procedure smoothing_main understood as hypsurfmain.smoothing_main
2 Command: Procedure computematrices_main understood as hypsurfmain.computematrices_main
3 Command: Procedure areafactor understood as hypsurfmain.areafactor
4 Command: Procedure findradius understood as hypsurfmain.findradius
5 Command: Procedure findratio understood as hypsurfmain.findratio
6 Command: unit march_main: not found
7 Command: Procedure compute_arc_length understood as hypsurfmain.compute_arc_length
8 Command: Procedure redistribute_nodes_by_arc_length understood as hypsurfmain.redistribute_nodes_by_arc_length
9 hypsurfmain: (DD15) Module precision is not defined
10 computematrices_main: (DD15) Module solveroutines is not defined
11 computematrices_main: (TC33) External procedure solve is not declared
12 computematrices_main: (AD09) Please provide a differential of function solve for arguments Arg1=(in) Arg2=(in;out) Arg3=(in)
13 qualitycheck: (TC19) Equality test on reals is not reliable
14 giveangle: (TC16) Type mismatch in assignment: REAL,kind=realtype  receives DOUBLE PRECISION
