!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.10 (r5363) -  9 Sep 2014 09:53
!
!
!      ******************************************************************
!      *                                                                *
!      * File:          precision.F90                                   *
!      * Author:        Edwin van der Weide                             *
!      * Starting date: 12-09-2002                                      *
!      * Last modified: 06-25-2005                                      *
!      *                                                                *
!      ******************************************************************
!
MODULE PRECISION_D
  IMPLICIT NONE
  SAVE 
!
!      ******************************************************************
!      *                                                                *
!      * Definition of the integer type used in the entire code. There  *
!      * might be a more elegant solution to do this, but be sure that  *
!      * compatability with MPI must be guaranteed. Note that dummyInt  *
!      * is a private variable, only used for the definition of the     *
!      * integer type. Note furthermore that the parameters defining    *
!      * the MPI types are integers. This is because of the definition  *
!      * in MPI.                                                        *
!      *                                                                *
!      ******************************************************************
!
! Standard 4 byte integer types are used as default integers.
  INTEGER(kind=4), PRIVATE :: dummyint
  INTEGER, PARAMETER :: sizeofinteger=4
!
!      ******************************************************************
!      *                                                                *
!      * Definition of the float type used in the entire code. The      *
!      * remarks mentioned before the integer type definition also      *
!      * apply here.                                                    *
!      *                                                                *
!      ******************************************************************
!
! Double precision reals are used as default real types.
  REAL(kind=8), PRIVATE :: dummyreal
  INTEGER, PARAMETER :: sizeofreal=8
  REAL(kind=8), PRIVATE :: dummycgnsreal
!
!      ******************************************************************
!      *                                                                *
!      * Definition of the porosity type. As this is only a flag to     *
!      * indicate whether or not fluxes must be computed, an integer1   *
!      * is perfectly okay.                                             *
!      *                                                                *
!      ******************************************************************
!
  INTEGER(kind=1), PRIVATE :: dummypor
!     ******************************************************************
!     *                                                                *
!     * Definition of the integer type for the element types. As only  *
!     * a limited number element types are present, a 1 byte integer   *
!     * is enough.                                                     *
!     *                                                                *
!     ******************************************************************
!
  INTEGER(kind=1), PRIVATE :: adtdummyelementint
!      ******************************************************************
!      *                                                                *
!      * Definition of the cgns periodic type.                          *
!      *                                                                *
!      ******************************************************************
!
  REAL(kind=4), PRIVATE :: dummycgnsper
!
!      ******************************************************************
!      *                                                                *
!      * Definition of the kind parameters for the integer and real     *
!      * types.                                                         *
!      *                                                                *
!      ******************************************************************
!
  INTEGER, PARAMETER :: inttype=KIND(dummyint)
  INTEGER, PARAMETER :: portype=KIND(dummypor)
  INTEGER, PARAMETER :: realtype=KIND(dummyreal)
  INTEGER, PARAMETER :: adtelementtype=KIND(adtdummyelementint)
  INTEGER, PARAMETER :: cgnsrealtype=KIND(dummycgnsreal)
  INTEGER, PARAMETER :: cgnspertype=KIND(dummycgnsper)
!
!      ******************************************************************
!      *                                                                *
!      * Definition of the reals use by the visualization package PV3.  *
!      * Note that PV3 expects all of its information to be passed back *
!      * as 4-byte (float) reals.                                       *
!      *                                                                *
!      ******************************************************************
!
  INTEGER(kind=4), PRIVATE :: dummyintpv3
  REAL(kind=4), PRIVATE :: dummyrealpv3
  INTEGER, PARAMETER :: intpv3type=KIND(dummyintpv3)
  INTEGER, PARAMETER :: realpv3type=KIND(dummyrealpv3)
!
!      ******************************************************************
!      *                                                                *
!      * Set the parameter debug, depending on the compiler option.     *
!      *                                                                *
!      ******************************************************************
!
  LOGICAL, PARAMETER :: debug=.false.
END MODULE PRECISION_D
