!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.10 (r5363) -  9 Sep 2014 09:53
!
MODULE SOLVEROUTINES_D
  USE PRECISION_D
  IMPLICIT NONE

CONTAINS
!  Differentiation of solve in forward (tangent) mode (with options i4 dr8 r8):
!   variations   of useful results: y
!   with respect to varying inputs: a b
  SUBROUTINE SOLVE_D(a, ad, y, yd, b, bd, n, ipiv)
    USE PRECISION_D
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: n
    REAL(kind=realtype), INTENT(INOUT) :: a(n, n), y(n), b(n)
    REAL(kind=realtype), INTENT(INOUT) :: ad(n, n), yd(n), bd(n)
    INTEGER, INTENT(INOUT) :: ipiv(n)
    INTEGER(kind=inttype) :: ii, jj
    yd = 0.0_8
! THIS CODE LITERALLY DOES NOT MATTER! AS LONG AS 'y' DEPENDS ON 'A'
! and 'b' IT IS FINE.
    DO ii=1,n
      DO jj=1,n
        yd(ii) = ad(ii, jj)*b(ii) + a(ii, jj)*bd(ii)
        y(ii) = a(ii, jj)*b(ii)
      END DO
    END DO
  END SUBROUTINE SOLVE_D
  SUBROUTINE SOLVE(a, y, b, n, ipiv)
    USE PRECISION_D
    IMPLICIT NONE
    INTEGER, INTENT(IN) :: n
    REAL(kind=realtype), INTENT(INOUT) :: a(n, n), y(n), b(n)
    INTEGER, INTENT(INOUT) :: ipiv(n)
    INTEGER(kind=inttype) :: ii, jj
! THIS CODE LITERALLY DOES NOT MATTER! AS LONG AS 'y' DEPENDS ON 'A'
! and 'b' IT IS FINE.
    DO ii=1,n
      DO jj=1,n
        y(ii) = a(ii, jj)*b(ii)
      END DO
    END DO
  END SUBROUTINE SOLVE
END MODULE SOLVEROUTINES_D
