!        generated by tapenade     (inria, tropics team)
!  tapenade 3.10 (r5363) -  9 sep 2014 09:53
!
module solveroutines_d
  use precision
  implicit none

contains
!  differentiation of solve in forward (tangent) mode (with options i4 dr8 r8):
!   variations   of useful results: y
!   with respect to varying inputs: a b
  subroutine solve_d(a, ad, y, yd, b, bd, n, ipiv)
    use precision
    implicit none
    integer, intent(in) :: n
    real(kind=realtype), intent(inout) :: a(n, n), y(n), b(n)
    real(kind=realtype), intent(inout) :: ad(n, n), yd(n), bd(n)
    integer, intent(inout) :: ipiv(n)
    integer(kind=inttype) :: ii, jj
    yd = 0.0_8
! this code literally does not matter! as long as 'y' depends on 'a'
! and 'b' it is fine.
    do ii=1,n
      do jj=1,n
        yd(ii) = ad(ii, jj)*b(ii) + a(ii, jj)*bd(ii)
        y(ii) = a(ii, jj)*b(ii)
      end do
    end do
  end subroutine solve_d
  subroutine solve(a, y, b, n, ipiv)
    use precision
    implicit none
    integer, intent(in) :: n
    real(kind=realtype), intent(inout) :: a(n, n), y(n), b(n)
    integer, intent(inout) :: ipiv(n)
    integer(kind=inttype) :: ii, jj
! this code literally does not matter! as long as 'y' depends on 'a'
! and 'b' it is fine.
    do ii=1,n
      do jj=1,n
        y(ii) = a(ii, jj)*b(ii)
      end do
    end do
  end subroutine solve
end module solveroutines_d
