!        Generated by TAPENADE     (INRIA, Tropics team)
!  Tapenade 3.10 (r5363) -  9 Sep 2014 09:53
!
!
!      ******************************************************************
!      *                                                                *
!      * File:          constants.F90                                   *
!      * Author:        Gaetan Kenway                                   *
!      * Starting date: 05-23-2010                                      *
!      * Last modified: 05-23-2010                                      *
!      *                                                                *
!      ******************************************************************
!
MODULE CONSTANTS_D
!
!      ******************************************************************
!      *                                                                *
!      * Definition of the constants used in the code.                  *
!      *                                                                *
!      ******************************************************************
!
  USE PRECISION_D
  IMPLICIT NONE
  SAVE 
! Maximum number of families
  INTEGER(kind=inttype), PARAMETER :: maxfamilies=128
! Maximum numbers of characters in a string and in a cgns name
  INTEGER(kind=inttype), PARAMETER :: maxstringlen=512
  INTEGER(kind=inttype), PARAMETER :: maxcgnsnamelen=32
! Numerical constants
  REAL(kind=realtype), PARAMETER :: pi=3.1415926535897931_realType
  REAL(kind=realtype), PARAMETER :: phi=2.1180339887498949
  REAL(kind=realtype), PARAMETER :: eps=1e-15
! Floating point parameters.
  REAL(kind=realtype), PARAMETER :: zero=0.0_realType
  REAL(kind=realtype), PARAMETER :: one=1.0_realType
  REAL(kind=realtype), PARAMETER :: two=2.0_realType
  REAL(kind=realtype), PARAMETER :: three=3.0_realType
  REAL(kind=realtype), PARAMETER :: four=4.0_realType
  REAL(kind=realtype), PARAMETER :: five=5.0_realType
  REAL(kind=realtype), PARAMETER :: six=6.0_realType
  REAL(kind=realtype), PARAMETER :: sevenp5=7.5_realType
  REAL(kind=realtype), PARAMETER :: eight=8.0_realType
  REAL(kind=realtype), PARAMETER :: ten=10.0_realType
  REAL(kind=realtype), PARAMETER :: twenty=20.0_realType
  REAL(kind=realtype), PARAMETER :: forty=40.0_realType
  REAL(kind=realtype), PARAMETER :: eighty=80.0_realType
  REAL(kind=realtype), PARAMETER :: onesixty=160.0_realType
  REAL(kind=realtype), PARAMETER :: threetwenty=320.0_realType
  REAL(kind=realtype), PARAMETER :: sixforty=640.0_realType
  REAL(kind=realtype), PARAMETER :: half=0.5_realType
  REAL(kind=realtype), PARAMETER :: third=one/three
  REAL(kind=realtype), PARAMETER :: fourth=0.25_realType
  REAL(kind=realtype), PARAMETER :: quarter=0.25_realType
  REAL(kind=realtype), PARAMETER :: sixth=one/six
  REAL(kind=realtype), PARAMETER :: eighth=0.125_realType
END MODULE CONSTANTS_D
